onboarding = false

[theme]
name = "tokyo-night"

[terminal]
new_cwd = "follow"

[keys]
next_tab = "ctrl+tab"
previous_tab = "ctrl+shift+tab"
switch_tab = "cmd+1..9"
new_tab = "prefix+t"
toggle_sidebar = "prefix+b"

[experimental]
kitty_graphics = true
