# https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
hooks.pre = "autoload -Uz compinit && compinit"
apply = ["defer"]

[plugins.zim-env]
github = "zimfw/environment"
apply = ["defer"]

[plugins.lazyload]
github = "qoomon/zsh-lazyload"

[plugins.mods]
local = "~/.config/zsh/modules"
use = ["*.zsh"]
apply = ["defer"]
