# https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]
[plugins.zim-env]
github = "zimfw/environment"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
hooks.post = "autoload -Uz compinit && compinit"

[plugins.autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
hooks.pre = """
ZVM_CURSOR_STYLE_ENABLED=true
ZVM_INSERT_MODE_CURSOR=$'\\e[5 q'
ZVM_NORMAL_MODE_CURSOR=$'\\e[2 q'
ZVM_VISUAL_MODE_CURSOR=$'\\e[2 q'
"""

[plugins.lazyload]
github = "qoomon/zsh-lazyload"

[plugins.mods]
local = "~/.config/zsh/modules"
use = ["*.zsh"]
apply = ["defer"]
